### PR TITLE
Update mormot.db.nosql.mongodb.pas

### PR DESCRIPTION
**Pull request by danielkuettner**
same changes I've sent per Email (perhaps easier to check and merge)

### CODE REVIEW

**Review by synopse — APPROVED** [review]
I guess I will integrate this with a runtime check of the WireProtocol, and allow connection on old and new MongoDB instances.
Checking the protocol version is what is required for a client, IIRC.

Thanks a lot for your input!

**Comment by danielkuettner** [comment]
Hi Arnaud,

thank you for patching my little changes.
I suggest to work with the ifdef and set it to the new protocol version. The old one is never needed and every body should be able to update MongoDB.
It seems that you don’t like Croatia?

Daniel

**Comment by synopse** [comment]
It does make sense to remote the old protocol.

My question with the current implementation is: how do you insert or update items?
The opcodes have been removed, but our driver still use opInsert and opUpdate :(

**Comment by danielkuettner** [comment]
I use only RunCommand, for inserts, updates and deletes too.

Therefore I don’t have touched these parts.

If you need my help…

Daniel

**Comment by synopse** [comment]
And for searches, I guess you use https://www.mongodb.com/docs/manual/reference/command/find/#mongodb-dbcommand-dbcmd.find ?

**Comment by danielkuettner** [comment]
No, RunCommand with aggregate too.

**Comment by danielkuettner** [comment]
You could encapsulate RunCommand for all your other classes (e.g. find, update, insert).

All other code would be obsolete

**Pull request merged**
