### PR TITLE
Added several curl_mime_* methods.

### PR DESCRIPTION
**Pull request by transmogrifix**

### CODE REVIEW

**Comment by synopse** [comment]
Thanks for the input!

**Comment by synopse** [comment]
Thanks for the input!

**Comment by synopse** [comment]
Your pull request needed some fixes for Android, i.e. for libcurl static linking.

**Comment by transmogrifix** [comment]
Yes, not sure how I missed that. Probably because it was disabled due to the conditional.
Thank you!

**Pull request merged**
