### PR TITLE
Introduced new overloaded function RunProcess().

### PR DESCRIPTION
**Pull request by the-real-wizard-of-oz**

### CODE REVIEW

**Comment by synopse** [comment]
My guess is that it won't compile on POSIX/non Windows, because both overloads would have the same signature.

**Comment by synopse** [comment]
And also PProcessInformation vs PHandle is very confusing. I suspect FPC or some Delphi would have troubles with it.

So, perhaps not an overload, but a new Windows-only method like `RunCommandWin()` returning PProcessInformation.

**Comment by the-real-wizard-of-oz** [comment]
Current commit compiles well on FPC. Should i rename RunProcess() to RunProcessWin() anyway?

**Comment by synopse** [comment]
Please see my last commit.
https://github.com/synopse/mORMot2/commit/5212b264

**Comment by synopse** [comment]
Closing for now, hoping my last commit fits your needs.
:)

Please reopen if it was not enough.
Thanks.

**Comment by the-real-wizard-of-oz** [comment]
RunProcessWin() seems fine, thanks.

**Pull request closed without merging**
