### PR TITLE
Update cURL API

### PR DESCRIPTION
**Pull request by dhewg**
Assorted updates I've been using for a while

### CODE REVIEW

**Comment by synopse** [comment]
This is a huge enhancement of the libcurl wrapper.
Nice!

Perhaps I would not touch as much the THttpRequest parent...
I will do some minor tweaks after merging.

Thanks a lot for your input!

**Comment by dhewg** [comment]
Yeah, the used curl api was a bit dated ;)
It's working flawless for me, including https/bearer/rest functionality ;)
Thanks for the fast merges!

**Comment by synopse** [comment]
There was some problems with FPC and I fixed some minor tweaks.

Please test and report on any issue.

Arnaud

**Comment by dhewg** [comment]
My https/smtps/rest cases all seem to work just fine, thanks!

**Comment by synopse** [comment]
I made some further refactoring for better code maintenance.

**Pull request merged**
