### PR TITLE
Update mormot.lib.curl.pas

### PR DESCRIPTION
**Pull request by danielkuettner**
Hi ab,

could you please add two consts needed for sftp/scp pub key auth?

Thanks,
Daniel

### CODE REVIEW

**Comment by synopse** [comment]
Hello Daniel,
Why did you close this PR?
It seemed fine to me.

**Comment by danielkuettner** [comment]
Sorry but I’m not aware of closing it. It were nice if you would merge it.

Daniel

**Comment by synopse** [comment]
I could not reopen and merge it, because you deleted your own repository.
But I have included the constants, with a small renaming for consistency with the original options.

**Comment by danielkuettner** [comment]
Thanks a lot!DanielAm 26.07.2024 um 08:36 schrieb ab ***@***.***>:﻿
I could not reopen and merge it, because you deleted your own repository.
But I have included the constants, with a small renaming for consistency with the original options.

**Pull request closed without merging**
